# Generated by Django 5.0.2 on 2024-03-11 06:56

from django.db import migrations


def populate_menu_items(apps, schema_editor): # noqa: unused-argument

    """
        Populates the MenuItems model with initial data.
    """

    menu_items = apps.get_model('coffeeshop', 'MenuItems')
    category = apps.get_model('coffeeshop', 'Category')

    hot_drinks_category = category.objects.get(name='hot drinks')

    menu_items.objects.create(
        name='latte',
        description='Description of latte',
        is_active=True,
        price=3.50,
        image='media/cover/latte.png',
        category=hot_drinks_category
    )
    menu_items.objects.create(
        name='tea',
        description='Description of tea',
        is_active=True,
        price=2.00,
        image='media/cover/tea.png',
        category=hot_drinks_category
    )


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0006_create_category'),
    ]

    operations = [
        migrations.RunPython(populate_menu_items),
    ]
