# Generated by Django 5.0.2 on 2024-03-11 09:52

from django.db import migrations


def create_category(apps, schema_editor): # noqa: unused-argument
    category = apps.get_model("coffeeshop", "Category")
    category.objects.create(name="ice cream", image="media/cover/ice_cream.png")
    category.objects.create(name="fast food", image="media/cover/Fast_Food_Picture.jpg")


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0007_populate_menuitems_for_first_category'),  # noqa: Typo in word 'menuitems'
    ]

    operations = [
        migrations.RunPython(create_category),
    ]
