# Generated by Django 5.0.2 on 2024-03-11 10:32

from django.db import migrations


def add_menu_items(apps, schema_editor): # noqa: unused-argument

    """
        Populates the MenuItems model.
    """

    menu_items = apps.get_model('coffeeshop', 'MenuItems')
    category = apps.get_model('coffeeshop', 'Category')

    fast_food_category = category.objects.get(name='fast food')
    ice_cream_category = category.objects.get(name='ice cream')

    menu_items.objects.create(
        name='Mushroom Meat Pizza',
        description='Delicious pizza with mushroom and meat toppings',
        is_active=True,
        price=12.99,
        image='media/cover/pizza.png',
        category=fast_food_category
    )

    menu_items.objects.create(
        name='Strawberry Ice Cream',
        description='Creamy strawberry-flavored ice cream',
        is_active=True,
        price=5.99,
        image='media/cover/strawberry_ice_cream.png',
        category=ice_cream_category
    )


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0008_create_two_other_category'),
    ]

    operations = [
        migrations.RunPython(add_menu_items),
    ]
