# Generated by Django 5.0.2 on 2024-03-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coffeeshop", "0009_populate_menu_items_by_two_other"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(null=True, unique=True, upload_to="media"),
        ),
    ]
